# Generated by Django 6.0.4 on 2026-05-16 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enseignants', '0008_enseignant_plafond_pfe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignant',
            name='plafond_pfe',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Capacité individuelle (laisser vide pour utiliser le plafond global).', null=True),
        ),
    ]
