# Generated by Django 6.0.4 on 2026-05-16 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enseignants', '0009_alter_enseignant_plafond_pfe'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='plafond_enseignement',
            field=models.PositiveIntegerField(blank=True, help_text="Plafond d'heures d'enseignement (cours/TD/TP).", null=True),
        ),
    ]
