# Generated by Django 6.0.4 on 2026-05-06 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academique', '0008_remove_module_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='departement',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='departements_photos/'),
        ),
    ]
