# Generated by Django 6.0.4 on 2026-05-06 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academique', '0009_departement_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licence',
            name='code',
        ),
        migrations.AddField(
            model_name='licence',
            name='domaine',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='licence',
            name='mention',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='licence',
            name='parcours',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
