# Generated by Django 6.0.4 on 2026-05-16 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academique', '0010_remove_licence_code_licence_domaine_licence_mention_and_more'),
        ('enseignants', '0010_enseignant_plafond_enseignement'),
    ]

    operations = [
        migrations.CreateModel(
            name='UEElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('coefficient', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('vh_c', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Volume horaire Cours')),
                ('vh_td', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Volume horaire TD')),
                ('vh_tp', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Volume horaire TP')),
                ('vh_ci', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Volume horaire CI')),
                ('sections', models.PositiveIntegerField(default=1, verbose_name='Nombre de sections')),
                ('groupes_td', models.PositiveIntegerField(default=1, verbose_name='Nombre de groupes TD')),
                ('sous_groupes_tp', models.PositiveIntegerField(default=1, verbose_name='Nombre de sous-groupes TP')),
                ('etudiants', models.PositiveIntegerField(default=0, verbose_name="Nombre d'étudiants")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('enseignant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ue_elements', to='enseignants.enseignant')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ue_elements', to='academique.module')),
            ],
            options={
                'verbose_name': 'Élément UE',
                'verbose_name_plural': 'Éléments UE',
                'ordering': ['module__nom', 'nom'],
            },
        ),
    ]
