# Generated by Django 6.0.4 on 2026-05-16 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academique', '0011_ueelement'),
        ('enseignants', '0010_enseignant_plafond_enseignement'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffectationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_cours', models.CharField(choices=[('C', 'Cours'), ('TD', 'TD'), ('TP', 'TP'), ('CI', 'Cours Intégré')], max_length=2)),
                ('groupe', models.CharField(blank=True, max_length=50, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations_details', to='enseignants.enseignant')),
                ('ue_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations_details', to='academique.ueelement')),
            ],
            options={
                'verbose_name': "Détail d'affectation",
                'verbose_name_plural': "Détails d'affectation",
                'unique_together': {('ue_element', 'type_cours', 'groupe')},
            },
        ),
    ]
