# Generated by Django 6.0.4 on 2026-05-06 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0004_alter_etudiant_numtel'),
        ('pfes', '0007_alter_pfe_encadrant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pfestudent',
            name='etudiant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pfe_assignment', to='etudiants.etudiant'),
        ),
    ]
