# Generated by Django 6.0.4 on 2026-05-15 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfes', '0009_pfe_lieu_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='soutenance',
            name='type_soutenance',
            field=models.CharField(choices=[('technique', 'Technique'), ('finale', 'Finale')], default='finale', help_text='Type de soutenance (Technique ou Finale).', max_length=20),
        ),
        migrations.AlterField(
            model_name='soutenance',
            name='duree',
            field=models.PositiveIntegerField(blank=True, help_text='Durée en minutes', null=True),
        ),
    ]
