# Generated by Django 6.0.4 on 2026-05-16 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfes', '0011_pfe_resultat_soutenance_finale_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pfe',
            name='resultat_soutenance_finale',
        ),
        migrations.RemoveField(
            model_name='pfe',
            name='resultat_soutenance_technique',
        ),
        migrations.AddField(
            model_name='soutenance',
            name='resultat_finale',
            field=models.CharField(blank=True, help_text="Résultat d'évaluation de Soutenance finale", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='soutenance',
            name='resultat_technique',
            field=models.CharField(blank=True, help_text="Résultat d'évaluation de Soutenance technique", max_length=100, null=True),
        ),
    ]
