# Generated by Django 6.0.4 on 2026-05-16 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfes', '0013_salle'),
    ]

    operations = [
        migrations.AddField(
            model_name='soutenance',
            name='depot_electronique',
            field=models.BooleanField(default=False, help_text='Dépôt électronique effectué (Oui/Non)'),
        ),
        migrations.AddField(
            model_name='soutenance',
            name='depot_papier',
            field=models.BooleanField(default=False, help_text='Dépôt papier effectué (Oui/Non)'),
        ),
    ]
