# Generated by Django 6.0.4 on 2026-05-19 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfes', '0015_add_type_projet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soutenance',
            name='pfe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soutenances', to='pfes.pfe'),
        ),
    ]
