# Generated by Django 6.0.4 on 2026-05-16 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enseignants', '0007_enseignant_departement_enseignant_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='plafond_pfe',
            field=models.PositiveSmallIntegerField(default=5, help_text="Nombre maximal d'étudiants/groupes que cet enseignant souhaite encadrer."),
        ),
    ]
