# Generated by Django 6.0.4 on 2026-05-06 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0005_etudiant_situation'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='groupe',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
