# Generated by Django 6.0.4 on 2026-05-22 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0010_rename_etudiant_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='passport',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
