# Generated by Django 6.0.4 on 2026-05-29 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0012_khalil'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Khalil',
        ),
    ]
