# Generated by Django 6.0.4 on 2026-05-29 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0014_etudiant_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='age',
        ),
    ]
