# Generated by Django 6.0.4 on 2026-05-06 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfes', '0008_alter_pfestudent_etudiant'),
    ]

    operations = [
        migrations.AddField(
            model_name='pfe',
            name='lieu_stage',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
