# Generated by Django 6.0.4 on 2026-05-16 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfes', '0010_soutenance_type_soutenance_alter_soutenance_duree'),
    ]

    operations = [
        migrations.AddField(
            model_name='pfe',
            name='resultat_soutenance_finale',
            field=models.CharField(blank=True, help_text="Résultat d'évaluation de Soutenance finale", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pfe',
            name='resultat_soutenance_technique',
            field=models.CharField(blank=True, help_text="Résultat d'évaluation de Soutenance technique", max_length=100, null=True),
        ),
    ]
