# Generated by Django 6.0.4 on 2026-05-29 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academique', '0012_affectationdetail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='affectationdetail',
            options={},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['annee', 'semestre', 'nom']},
        ),
        migrations.AlterModelOptions(
            name='ueelement',
            options={'ordering': ['module__nom', 'nom']},
        ),
        migrations.AlterField(
            model_name='module',
            name='coefficient_ue',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='module',
            name='credit_ue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='module',
            name='matieres',
            field=models.JSONField(blank=True, default=list, help_text='Liste des matières (ECUEs)'),
        ),
        migrations.AlterField(
            model_name='ueelement',
            name='etudiants',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ueelement',
            name='groupes_td',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ueelement',
            name='sections',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ueelement',
            name='sous_groupes_tp',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ueelement',
            name='vh_c',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='ueelement',
            name='vh_ci',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='ueelement',
            name='vh_td',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='ueelement',
            name='vh_tp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
