# Generated by Django 6.0.4 on 2026-05-31 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academique', '0013_alter_affectationdetail_options_alter_module_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='licence',
            old_name='parcours',
            new_name='specialite',
        ),
    ]
