# Generated by Django 6.0.4 on 2026-05-06 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0004_alter_etudiant_numtel'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='situation',
            field=models.CharField(choices=[('N', 'Nouveau'), ('R', 'Redoublant')], default='N', max_length=1),
        ),
    ]
