# Generated by Django 6.0.4 on 2026-05-15 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0006_etudiant_groupe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etudiant',
            old_name='situation',
            new_name='situation_s5',
        ),
        migrations.AddField(
            model_name='etudiant',
            name='situation_pfe',
            field=models.CharField(choices=[('N', 'Nouveau'), ('R', 'Redoublant')], default='N', max_length=1),
        ),
    ]
