# Generated by Django 6.0.4 on 2026-05-15 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0007_rename_situation_etudiant_situation_s5_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='annee_universitaire',
            field=models.CharField(default='2025/2026', max_length=9),
        ),
    ]
