# Generated by Django 6.0.4 on 2026-05-16 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0008_etudiant_annee_universitaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='genre',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], default='M', max_length=1),
        ),
    ]
