# Generated by Django 6.0.4 on 2026-05-29 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0013_delete_khalil'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
